// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8vI13PRo7l-l1O8FoeUqqCRG1AqF2VBU',
    appId: '1:865397589806:web:1dbf76e1ccb0bce96edcbf',
    messagingSenderId: '865397589806',
    projectId: 'retro-game-box',
    authDomain: 'retro-game-box.firebaseapp.com',
    storageBucket: 'retro-game-box.appspot.com',
    measurementId: 'G-CN4WEE4JZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbAF6FHxVGvtawHjWuMbR53N_dPljvOCk',
    appId: '1:865397589806:android:63bd8e4e137c22426edcbf',
    messagingSenderId: '865397589806',
    projectId: 'retro-game-box',
    storageBucket: 'retro-game-box.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAShyT9GGAqt-kPG5yVU7P0LssYtpeblpc',
    appId: '1:865397589806:ios:2100d3aa2821418a6edcbf',
    messagingSenderId: '865397589806',
    projectId: 'retro-game-box',
    storageBucket: 'retro-game-box.appspot.com',
    iosBundleId: 'com.example.retroGameBox',
  );
}
